Daigotanaka0714/client/change_to_server_mode
dancer-support/dance-tech-main pull request #268
Opened 2021-11-13 04:10 UTC by daigotanaka0714

## orverivew
- nuxtをstaticからserver modeに変更
- package.jsonのスクリプトに `lint:ifx` を追加し、`yarn lint:fix` でlint手元の環境で動作するように変更
- client/index.jsをlint

2021-11-13 04:15 UTC, daigotanaka0714 reviewed
いくつかコメントしてるので時間ある時に確認してもらえると助かります:bow:

2021-11-13 04:15 UTC, daigotanaka0714 commented on nuxt.config.js
> -  target: 'static',
netlifyに繋がってるようだけど、これを外すと動かないかも。。。

2021-11-13 04:15 UTC, daigotanaka0714 commented on api/index.js
> +}
package.jsonの `yarn lint:fix` でこんな感じにlintするようになってます。
reqはlintで引っかかったのでres.sendに含めるようにしてます。

2021-11-14 06:07 UTC, y-yeah requested changes
@daigotanaka0714 
ProcfileとREADME、.editorconfigはルートディレクトリに配置してもらえますか？

2021-11-14 07:09 UTC, y-yeah approved these changes
@daigotanaka0714 @ryo-takaya 
Herokuはこちらで直しときます〜。
.envだけDMで共有お願いします。

2021-11-14 07:25 UTC, merged