fit ci for docker compose
dancer-support/dance-tech-main pull request #341
Opened 2022-02-14 13:19 UTC by daigotanaka0714

## orver view
- fix github action for docker compose

## detail
- github actionでdockerのイメージ内で実行できるようにしてます

2022-02-14 14:55 UTC, bp-sumi requested changes

2022-02-14 14:55 UTC, bp-sumi commented on client/layouts/default.vue
> +        console.log('logout')
こちら消去で良い気がします。

2022-02-14 14:55 UTC, bp-sumi commented on .github/workflows/ci.yml
> +        run: docker-compose run --rm client yarn
46行目でもう立ち上がってるので、 `docker-compose exec client yarn` で良い気がします。

2022-02-14 14:55 UTC, bp-sumi commented on .github/workflows/ci.yml
> +        run: docker compose run --rm client yarn lint
こちらも同様です。あとコンポーズは2系に揃えたほうがいい気もします。

2022-02-17 11:58 UTC, y-yeah approved these changes

2022-02-17 11:58 UTC, merged